// Code generated by Wire protocol buffer compiler, do not edit.
// Source: buf.connect.demo.eliza.v1.ConverseResponse in simple.proto
package buf.connect.demo.eliza.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * ConverseResponse describes the sentence responded by the ELIZA program.
 */
public class ConverseResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val sentence: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ConverseResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ConverseResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (sentence != other.sentence) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + sentence.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """sentence=${sanitize(sentence)}"""
    return result.joinToString(prefix = "ConverseResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(sentence: String = this.sentence, unknownFields: ByteString = this.unknownFields):
      ConverseResponse = ConverseResponse(sentence, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ConverseResponse> = object : ProtoAdapter<ConverseResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ConverseResponse::class, 
      "type.googleapis.com/buf.connect.demo.eliza.v1.ConverseResponse", 
      PROTO_3, 
      null, 
      "simple.proto"
    ) {
      public override fun encodedSize(`value`: ConverseResponse): Int {
        var size = value.unknownFields.size
        if (value.sentence != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.sentence)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ConverseResponse): Unit {
        if (value.sentence != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.sentence)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ConverseResponse): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.sentence != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.sentence)
      }

      public override fun decode(reader: ProtoReader): ConverseResponse {
        var sentence: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> sentence = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ConverseResponse(
          sentence = sentence,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ConverseResponse): ConverseResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
