// Code generated by Wire protocol buffer compiler, do not edit.
// Source: buf.connect.demo.eliza.v1.ElizaService in simple.proto
package buf.connect.demo.eliza.v1

import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service

/**
 * ElizaService provides a way to talk to the ELIZA, which is a port of
 * the DOCTOR script for Joseph Weizenbaum's original ELIZA program.
 * Created in the mid-1960s at the MIT Artificial Intelligence Laboratory,
 * ELIZA demonstrates the superficiality of human-computer communication.
 * DOCTOR simulates a psychotherapist, and is commonly found as an Easter
 * egg in emacs distributions.
 */
public interface ElizaServiceClient : Service {
  /**
   * Converse is a bi-directional streaming request demo. This method should allow for
   * many requests and many responses.
   */
  public fun Converse(): GrpcStreamingCall<ConverseRequest, ConverseResponse>
}
