// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.kotlin.simple.ExternalMessage in external_message.proto
package com.squareup.protos.kotlin.simple

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ExternalMessage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
  )
  public val f: Float? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ExternalMessage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ExternalMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (f != other.f) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (f?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (f != null) result += """f=$f"""
    return result.joinToString(prefix = "ExternalMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(f: Float? = this.f, unknownFields: ByteString = this.unknownFields):
      ExternalMessage = ExternalMessage(f, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ExternalMessage> = object : ProtoAdapter<ExternalMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      ExternalMessage::class, 
      "type.googleapis.com/squareup.protos.kotlin.simple.ExternalMessage", 
      PROTO_2, 
      null, 
      "external_message.proto"
    ) {
      public override fun encodedSize(`value`: ExternalMessage): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.FLOAT.encodedSizeWithTag(1, value.f)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ExternalMessage): Unit {
        ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.f)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ExternalMessage): Unit {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.f)
      }

      public override fun decode(reader: ProtoReader): ExternalMessage {
        var f: Float? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> f = ProtoAdapter.FLOAT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ExternalMessage(
          f = f,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ExternalMessage): ExternalMessage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
